### ISSUE TITLE
Server SimSpeed dropping

### ISSUE THREAD

**Issue by Torkiwi** [Lazalatin/space-engineers-dedicated-ubuntu-docker-server#7]
SimSpeed is at 1.00 ~1.02 then will drop around 0.88 for ~1s every 10s or so.

Still looking into it as simspeed drops can come from anywhere.
So really, how is your simSpeed :  Stable, fluctuating, always bad ?

Removed All InGame Causes that i could think of : 
- [x] Mods
- [x] EmptyWorld
- [x] No Asteroids / Planet
- [x] Drop Containers
- [x] Encounters
- [x] Drones
- [x] Cargo Ships
- [x] Economy
- [x] Ingame Scripts
- [x] Experimental Mode
- [x] Airtightness
- [x] Oxygen
- [x] World Size
- [x] Trash Removal
- [x] World Size

I've included the Sandbox.sbc for reference

[Sandbox.zip](https://github.com/Lazalatin/space-engineers-dedicated-ubuntu-docker-server/files/3757186/Sandbox.zip)

**Comment by Lazalatin** [comment]
Hi @Torkiwi,
First, again, thank you for your effort!

It is a pity, but actually my gaming rig is not available at the time, because I was moving lately and was not able to build my setup up again. This will likely happen until mid November.

So as simulation speed is determined by the slowest of the machines in a multiplayer game, I can not contribute to these investigations you have listed until then.

But I may point you to some other hints. There are some directions in the protonDB entry for Space Engineers: https://www.protondb.com/app/244850

Some of them mention `esync` as a reason for slow SimSpeed: https://github.com/ValveSoftware/Proton#runtime-config-options

But I already noticed that this appears only to be active on `proton`, so we may try to change from `wine` to `proton` and try again. I will try to do that in the following days.

**Comment by Torkiwi** [comment]
I'll try my best to remove all  possible simspeed drops from Ingame to have a cleaner view of where we are standing. 
But the same save file on windows DS runs smoothly at a constant 1.00 ~1.02.
Which means other leads will need to be followed. ( and esync could be a good one !)
 I'm just removing background noise for now really^^

**Comment by Torkiwi** [comment]
Small Update :

I've removed all the Ingame causes i could think of with no visible impact on SimSpeed,
I've included the [Sandbox.sbc](url) for reference in the first post.
@Lazalatin  I saw you started on the **proton branch** ! 👍 
Can't wait to give it a spin !

**Comment by Lazalatin** [comment]
@Torkiwi Thank you for your Sandbox.cfg
I already started with the proton branch, but got stuck with trying to get `proton` precompiled within  the image with steamcmd.

It seems that I will have to add `proton` by compiling it withing the container. Which will take some time. But it will result in a more controlled environment so I will try this task.

This will likely result in a new repository. I will add it here as soon as I managed to create it.

**Comment by Torkiwi** [comment]
Hey @Lazalatin  ! 

How are things looking for proton ?

**Comment by Lazalatin** [comment]
Hi @Torkiwi,
Thanks for checking in!

I was on a vacation trip recently, so I had neither the time nor the possibility to work further on it. I will continue my experiments this week.

**Comment by Lazalatin** [comment]
Soo, long time no see.
As for now, I dropped my experiments using proton. This is mainly because I recently got a push to another direction and will maybe turn this project into a more universal systemd-based solution. Until then, some insights:

I recently got to know, taht in my case it was sufficient to put my servers cpu up a higher power level to stabilize the server. It is now running at ~3.7GHz to 4.1GHz. This made the server run more smoothly.

Until something new comes up, I will close this issue.
