### ISSUE TITLE
(minor) Dockerfile cache cleanup

### ISSUE THREAD

**Issue by zokradonh** [Lazalatin/space-engineers-dedicated-ubuntu-docker-server#9]
Thank you for this project. Just one minor suggestion for your Dockerfile:

You always try to clean up your apt-get installation caches etc. but this is without real effect if you do it in a separate layer (in a separate RUN instruction).
See the official Docker [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run) guide to see how to cleanup apt-get cache.

If you split them in separate RUN instructions the final image will have a layer with all the caches and a layer with instructions to delete the files. You will not save anything in your final image.
Always cleanup the mess in same RUN instruction.

**Comment by Lazalatin** [comment]
Well this was more or less a "get it at least running"-stage of the image. Most of the `RUN` fragmentations occurred during debugging the image :wink:

Nevertheless @wmark did a great job with his PR, which I merged into `master` right now.
Needs some testing though. But as far as I am concerned this issue is resolved with the merged PR. Feel free to reopen it, if necessary! :+1:
